spring.application.name=pocketpayapi

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pocketpay_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# App
server.port=8080
app.jwt.secret=${JWT_SECRET:pocketpay-super-secret-jwt-key-make-this-long-enough-256-bits}
app.jwt.expiration=86400000

# Paystack
paystack.secret.key=${PAYSTACK_SECRET_KEY:sk_test_placeholder}
paystack.base.url=https://api.paystack.co